"""initial migration

Revision ID: 0c0aa973f84e
Revises: 
Create Date: 2026-02-09 11:43:17.320907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0aa973f84e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('pkid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('pkid'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_nome'), 'pacientes', ['nome'], unique=True)
    op.create_index(op.f('ix_pacientes_pkid'), 'pacientes', ['pkid'], unique=False)
    op.create_table('profissionais',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('pkid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('pkid'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_profissionais_pkid'), 'profissionais', ['pkid'], unique=False)
    op.create_table('servicos',
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria', sa.Enum('CONSULTA', 'TERAPIA', name='categoriaservico'), nullable=False),
    sa.Column('preco_padrao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pkid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('pkid'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_servicos_pkid'), 'servicos', ['pkid'], unique=False)
    op.create_table('usuarios',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('pkid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('pkid'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_pkid'), 'usuarios', ['pkid'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('lancamentos',
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('data_competencia', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pagamento', sa.Enum('PIX', 'DINHEIRO', 'CARTAO_CREDITO', 'CARTAO_DEBITO', name='metodopagamento'), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('servico_id', sa.UUID(), nullable=False),
    sa.Column('profissional_id', sa.UUID(), nullable=True),
    sa.Column('pkid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('pkid'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_lancamentos_pkid'), 'lancamentos', ['pkid'], unique=False)
    op.create_table('user_refresh_tokens',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('pkid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('pkid'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_refresh_tokens_pkid'), 'user_refresh_tokens', ['pkid'], unique=False)
    op.create_index(op.f('ix_user_refresh_tokens_token_hash'), 'user_refresh_tokens', ['token_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_refresh_tokens_token_hash'), table_name='user_refresh_tokens')
    op.drop_index(op.f('ix_user_refresh_tokens_pkid'), table_name='user_refresh_tokens')
    op.drop_table('user_refresh_tokens')
    op.drop_index(op.f('ix_lancamentos_pkid'), table_name='lancamentos')
    op.drop_table('lancamentos')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_pkid'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_servicos_pkid'), table_name='servicos')
    op.drop_table('servicos')
    op.drop_index(op.f('ix_profissionais_pkid'), table_name='profissionais')
    op.drop_table('profissionais')
    op.drop_index(op.f('ix_pacientes_pkid'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_nome'), table_name='pacientes')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
