"""remove preço padrão2

Revision ID: 42038dd1c8c9
Revises: 9cf0fa654c2a
Create Date: 2026-02-10 17:08:16.130739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42038dd1c8c9'
down_revision: Union[str, Sequence[str], None] = '9cf0fa654c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicos', 'preco_padrao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos', sa.Column('preco_padrao', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
